name: Linux

on:
  push:
    branches: [ "main", "release-**" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - run: mvn -B package

      - name: Package into app-image
        run: |
          rm -rf build/launcher
          jpackage --input target/ --name launcher --main-jar launcher-0.1.0.jar --main-class chromaforge.launcher.Launcher --type app-image --dest build/ --java-options '-Dfile.encoding=UTF-8'

      - run: ./build/launcher/bin/launcher version
      - run: ./build/launcher/bin/launcher fetch
      - run: sudo apt-get update && sudo apt-get install -y libfuse2
      - run: ./build/launcher/bin/launcher install 0.4.1
      - run: ./build/launcher/bin/launcher new test 0.4.1
      - run: ./build/launcher/bin/launcher launch test
