name: Windows

on:
  push:
    branches: [ "main", "release-**" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - run: mvn -B package

      - name: Package into exe (app-image)
        shell: pwsh
        run: |
          if (Test-Path build\launcher) { Remove-Item -Recurse -Force build\launcher }
          jpackage --input target/ --name launcher --main-jar launcher-0.1.0.jar --main-class chromaforge.launcher.Launcher --type app-image --dest build/ --java-options '-Dfile.encoding=UTF-8' --win-console

      - run: build\launcher\launcher.exe version
      - run: build\launcher\launcher.exe fetch
      - run: build\launcher\launcher.exe install 0.4.1
      - run: build\launcher\launcher.exe launch 0.4.1
